name: Waka Full Readme

on:
  schedule:
    # Runs at 12am IST
    - cron:  '0 8,13,20 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka-Readme # optional
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_EDITORS: True
          SHOW_TIMEZONE: false
          SHOW_COMMIT: True
          SHOW_LANGUAGE: True
          SHOW_LINES_OF_CODE: False
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_LOC_CHART: false
          SHOW_DAYS_OF_WEEK: True
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: false
          SHOW_UPDATED_DATE: false
          SHOW_TOTAL_CODE_TIME: false
          COMMIT_BY_ME: False
          COMMIT_MESSAGE: Updated with Dev Metrics
          COMMIT_SINGLE: False
          LOCALE: en
